_wandb:
    value:
        cli_version: 0.18.3
        m:
            - "1": Confusion Matrix._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": Confusion Matrix.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Confusion Matrix.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val/val_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Confusion Matrix.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Confusion Matrix.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Confusion Matrix.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/train_acc_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val/val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/train_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Confusion Matrix.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/train_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/train_acc_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.5
            "5": 0.18.3
            "6": 4.45.1
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-arm64
